import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage();
p.on('pageerror', e => console.log('PAGE-ERR:', String(e).slice(0,160)));
await p.goto('http://localhost:5173/connexion');
await p.locator('input').first().fill('admin');
await p.locator('input[type="password"], input.pr-10').first().fill('EmMn@2026!Demo');
await p.click('button[type="submit"]');
await p.waitForURL('http://localhost:5173/', { timeout: 15000 });
await p.goto('http://localhost:5173/effectifs');
await p.waitForSelector('button:has-text("Nouvelle fiche")', { timeout: 15000 });
await p.click('button:has-text("Nouvelle fiche")');
await p.waitForSelector('text=Étape 1 sur 3', { timeout: 10000 });
const e1 = (await p.locator('body').textContent()).includes('Étape 1 sur 3');
const inputs = p.locator('input');
await inputs.nth(1).fill('MSA/2026/999');
await inputs.nth(2).fill('1990-01-15');
await inputs.nth(3).fill('TEST');
await inputs.nth(4).fill('Wizard');
await p.waitForTimeout(400);
await p.click('button:has-text("Suivant")');
await p.waitForSelector('text=Étape 2 sur 3', { timeout: 10000 });
const e2 = true;
await p.locator('select').nth(0).selectOption({ index: 1 });
await p.locator('select').nth(1).selectOption({ index: 1 });
await p.waitForTimeout(400);
await p.click('button:has-text("Suivant")');
await p.waitForSelector('text=Étape 3 sur 3', { timeout: 10000 });
const body3 = await p.locator('body').textContent();
const e3 = (body3 ?? '').includes('Étape 3 sur 3');
const recap = (body3 ?? '').includes('TEST Wizard');
const segments = await p.locator('ol > li').count();
console.log('étape 1 :', e1, '| étape 2 :', e2, '| étape 3 :', e3, '| récap :', recap, '| segments :', segments);
await b.close();
process.exit(e1 && e2 && e3 && recap && segments === 3 ? 0 : 1);
